# Generated by Django 4.0.4 on 2022-04-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='DOB',
            field=models.DateField(),
        ),
    ]
