# Generated by Django 4.0.4 on 2022-04-20 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
        ('movies', '0007_alter_movie_average_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='star',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='actors.actor'),
        ),
    ]
